export function createSeedState() {
  return {
    meta: {
      version: 1,
      demoReady: false,
      updatedAt: new Date().toISOString(),
      sequence: {
        order: 1,
        receivable: 1,
        purchase: 1,
        movement: 1,
      },
    },
    customers: [
      {
        id: "CUS-001",
        name: "众鑫五金总汇",
        tier: "A",
        owner: "陈旭",
        phone: "13800010001",
        city: "上海",
        creditLimit: 80000,
        paymentTermDays: 30,
      },
      {
        id: "CUS-002",
        name: "海川装饰工程",
        tier: "B",
        owner: "赵峰",
        phone: "13800010002",
        city: "苏州",
        creditLimit: 50000,
        paymentTermDays: 15,
      },
      {
        id: "CUS-003",
        name: "城东机电门市",
        tier: "C",
        owner: "孙强",
        phone: "13800010003",
        city: "嘉兴",
        creditLimit: 20000,
        paymentTermDays: 7,
      },
      {
        id: "CUS-004",
        name: "品创弱电安装队",
        tier: "B",
        owner: "林霖",
        phone: "13800010004",
        city: "昆山",
        creditLimit: 35000,
        paymentTermDays: 10,
      },
    ],
    products: [
      {
        id: "PRD-001",
        sku: "JG-M8-80",
        name: "膨胀螺栓 M8*80",
        category: "紧固件",
        brand: "固锋",
        spec: "M8 x 80",
        unit: "盒",
        basePrice: 38,
        stock: {
          onHand: 140,
          reserved: 0,
          reorderPoint: 40,
        },
      },
      {
        id: "PRD-002",
        sku: "HJ-304-4",
        name: "304 不锈钢合页 4寸",
        category: "门窗配件",
        brand: "海虎机械",
        spec: "4 寸",
        unit: "付",
        basePrice: 16,
        stock: {
          onHand: 60,
          reserved: 0,
          reorderPoint: 20,
        },
      },
      {
        id: "PRD-003",
        sku: "XC-PVC-2414",
        name: "PVC 线槽 24x14",
        category: "电工辅料",
        brand: "立通",
        spec: "24 x 14",
        unit: "根",
        basePrice: 12,
        stock: {
          onHand: 90,
          reserved: 0,
          reorderPoint: 30,
        },
      },
      {
        id: "PRD-004",
        sku: "QJ-100-50",
        name: "热镀锌桥架 100x50",
        category: "桥架",
        brand: "盛达",
        spec: "100 x 50",
        unit: "节",
        basePrice: 82,
        stock: {
          onHand: 8,
          reserved: 0,
          reorderPoint: 12,
        },
      },
      {
        id: "PRD-005",
        sku: "QGP-105",
        name: "切割片 105mm",
        category: "工具耗材",
        brand: "锐切",
        spec: "105 mm",
        unit: "盒",
        basePrice: 24,
        stock: {
          onHand: 32,
          reserved: 0,
          reorderPoint: 10,
        },
      },
      {
        id: "PRD-006",
        sku: "BXG-6-60",
        name: "自攻螺丝 6*60",
        category: "紧固件",
        brand: "匠拓",
        spec: "6 x 60",
        unit: "盒",
        basePrice: 29,
        stock: {
          onHand: 44,
          reserved: 0,
          reorderPoint: 18,
        },
      },
    ],
    orders: [],
    receivables: [],
    purchaseTasks: [],
    inventoryMovements: [],
  };
}

